#!/bin/bash

#SBATCH --job-name=simple-gpu    # Job name
#SBATCH --output=../job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8       # Schedule one core
#SBATCH --gres=gpu               # Schedule a GPU
#SBATCH --time=05:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red,brown        # Run on either the Red or Brown queue

module load CUDA
echo "Running on $(hostname):"
srun python3 main_train.py --quickselect 1
